### ISSUE TITLE
Server charset is ZHS16GBK, client nls_lang is UTF8, lost last characters

### ISSUE THREAD

**Issue by andygeng** [vrogier/ocilib#119]
Hi Vincent,

In ZHS16GBK, each Chinese character occupy 2 bytes.
In UTF8, each Chinese character occupy 3 bytes.

1. Server character set is zhs16gbk
create table T_VARCHAR
(
  id   NUMBER,
  name VARCHAR2(20)
)
insert into t_varchar(1, '你好世界你好世界你好'); --20 bytes(10 characters)
commit;

2. Program specify UTF8, only get 18 bytes(6 characters).
int main_test_varchar()
{
	OCI_Connection *cn;
	OCI_Statement  *st;
	OCI_Resultset  *rs;
	SetEnvironmentVariable("NLS_LANG", ".UTF8");
	if (!OCI_Initialize(err_handler, NULL, OCI_ENV_DEFAULT))
	{
		return EXIT_FAILURE;
	}
	cn = OCI_ConnectionCreate("192.168.253.1/test32", "andy2", "andy2", OCI_SESSION_DEFAULT);
	st = OCI_StatementCreate(cn);
	OCI_ExecuteStmt(st, "select * from andy.t_varchar");
	rs = OCI_GetResultset(st);  --need to triple/double varchar buffer size.
	while (OCI_FetchNext(rs))
	{
		printf("id: %i, name %s\n", OCI_GetInt(rs, 1), OCI_GetString(rs, 2));
	}
	printf("\n%d row(s) fetched\n", OCI_GetRowCount(rs));
	OCI_StatementFree(st);
	OCI_ConnectionFree(cn);
	OCI_Cleanup();
	return EXIT_SUCCESS;
}

**Comment by vrogier** [comment]
Hi,

can you verify that internal global static variable OCILib.nls_utf8  is set to 1 ?
Because, in this case, in column.c, method OCI_ColumnMap(), line 421, we have

  `c
ub2 char_size = (ub2) ( (OCILib.nls_utf8 ) ? UTF8_BYTES_PER_CHAR : sizeof(otext) );
`

and then later at line 751

 `c
col->bufsize  = (ub4) ((col->size + 1) * char_size);
`

Thus the buffer shall be big enought as UTF8_BYTES_PER_CHAR  is 4

col->size is computed from the value of OCI_ATTR_DATA_SIZE on the given column. 
It is the number of bytes the column can hold on server side.
In your example, column is 20 char of UTF16 codepoint => it shall be equal to 40
Then bufsize shall be equal to (40+1) * 4 = 164 bytes.
Enought to hold 53 characters UTF8.
The calculation is in fact weird as it should be (20+1) * 4.
But OCILIB does not know the size of the server charset codepoints.
With worse UTF8 case, 20 chars would require 81 bytes buffers.
Anyway, buffers seems big enough.
Can you check what is col->size value  is ?

thanks
 
vincent

**Comment by vrogier** [comment]
Hi,

Any news ?

regards,

vincent

**Comment by andygeng** [comment]
Sorry for delay.
I checked OCI_Initialize() funcition, you use getenv() function to get env variables.
But in Windows, most of time, it is set by SetEnvironmentVariable(), and get by GetEnvironmentVariable().
After I specify OCILib.nls_utf8 = 1 manually, it works.
Thanks.

  if (OCI_CHAR_ANSI == OCILib.charset)
    {
        char *str = getenv("NLS_LANG");

        if (str)
        {
            char nls_lang[OCI_SIZE_OBJ_NAME + 1] = "";

            strncat(nls_lang, str, OCI_SIZE_OBJ_NAME);

            for (str = nls_lang; *str; str++)
            {
                *str = (char) toupper(*str);
            }

            OCILib.nls_utf8 = (NULL != strstr(nls_lang, "UTF8"));
        }
		OCILib.nls_utf8 = 1;
    }

**Comment by vrogier** [comment]
Hi,

Microsoft implementation of putenv() and getenv() are using the Win32 calls
you've mentioned.
I thing it is more about when/where you set the the variable. It might be
not set or inherited in the environment of the ocilib process when
oci_initialize() is called.

Regards,

Vincent
