### ISSUE TITLE
OCI_GetString on date column drops the time portion of the date 

### ISSUE THREAD

**Issue by bangusi** [vrogier/ocilib#147]
```
	OCI_ExecuteStmt(st, L"select sysdate dt from dual");
	OCI_Resultset *rs = OCI_GetResultset(st);
	while (OCI_FetchNext(rs))
	{
		std::wcout << OCI_GetString(rs, 1) << std::endl;
	}
```
prints 2018-03-03 instead of 2018-03-03 20:51:14
Env: Windows 7, MVC 2017, Oracle client 12, server 12

**Comment by cjbj** [comment]
What are your environment and session settings?:

```
SQL> select sysdate from dual;

SYSDATE
---------
04-MAR-18

SQL> alter session set NLS_DATE_FORMAT = 'DD-MON-YY HH:MI:SS';

Session altered.

SQL> select sysdate from dual;

SYSDATE
------------------
04-MAR-18 05:01:39
```

**Comment by vrogier** [comment]
Hello,

This is an intended behaviour. 
When using OCI_GetString() with non character based columns, I had decided (since v1.0) to reproduce by default the same output than SQL*Plus.
In that case, as Chris mentioned, SQL*Plus omits the time portion by default.
You can change OCI_GetString()  default behaviour by setting your own date format  using  OCI_SetFormat().

Regards,

Vincent
