### ISSUE TITLE
vcpkg port request

### ISSUE THREAD

**Issue by bangusi** [vrogier/ocilib#214]
FYI an issue https://github.com/microsoft/vcpkg/issues/8187 was opened to have vcpkg distribution of ocilib.
I think it is a good idea

**Comment by vrogier** [comment]
Hi,

Yes, might be good idea! 
Added in my ToDo list.

Thanks

Vincent

**Comment by victorburckel** [comment]
Hi,

I did a pull request to vcpkg for ocilib integration:
https://github.com/microsoft/vcpkg/pull/11549

I hope this is ok for you, it should work for windows dynamic build and linux builds. 
Two things I noticed while integrating the lib:
- vcpkg performs out of source builds, so I had to adapt the configure script as if in https://github.com/vrogier/ocilib/blob/8587fbeb7eb86506496f77a40c91bdc89de337cf/acocilib.m4#L69 the code was relative to srcdir
```diff
-OCILIB_VER=`cat VERSION`
+OCILIB_VER=`cat ${srcdir}/VERSION`
```
- there is no debug configuration in the vs projects, so I just copied the release binaries in the debug folders, I don't know if it's worth adding debug configuration with optimization disabled (there's also no static library configuration, that's why in my vcpkg port the windows static build is expected to fail).

**Comment by vrogier** [comment]
Hi,

Thanks for sharing this :)

I had a quick look at the PR and here is some open questions:
- No support for building wide character version of ocilib ?
- do you want me to fix configure script ?
- do you really need a debug target ?
- OCI does not support ARM based platforms

Regards,

Vincent

**Comment by bangusi** [comment]
- No static builds?
I am not sure if there are practical limitations for supporting static builds since we have to link to oci.lib.
All my vcpkg libraries are  x64-windows-static

**Comment by victorburckel** [comment]
Hi,
Thanks for your comments,
- Yes for the wide char support, I didn't add it at first, it can be added in a second time, I don't know what's the best option, either always compile both, or add a "feature" in vcpkg, which would switch from ansi to wide char, so you would have to `vcpkg install ocilib[wchar]` to compile the wchar version ocilib, and simple `vcpkg install ocilib` to compile the ansi one.
- Yes if you could update acocilib.m4 and update then update the configure script in would be nice, we wouldn't have to apply a patch in vcpkg to compile newer versions of the lib
- As far as I'm concerned, I'm fine with using the same version of the lib wether in debug and release builds of my application, so if nobody needs them, there's no need to add such a configuration.
- For the previous versions of the solution, as you're the maintainer of the lib I guess it's up to you if to decide if you want to support out of the box older versions of the product, I understand that it can be quite painful to update all projects whenever you want to update the compilation commands / if you have to make workarounds for the compiler. 
- As far as I'm concerned (I don't have any knowledge of all the tools available, the advantages of each one, ...), I like the idea of build system generators like cmake (or I guess autoconf automake but I never used them so I don't know how it interacts with msvc), so that you can let the generator generate all the possible configurations, but switching to another system is not always easy, and maintaining multiple systems is not an option either. Finally having the vsproj directly in the repo makes it easier for windows users to get and compile the library.

**Comment by victorburckel** [comment]
Hello @bangusi, as the vcpkg portfile uses the vcxproj from the repo to build the library for windows, as there is no static build configuration, you have to use the dynamic version of the lib. I guess the practical reason is that it's always harder to maintain multiple and test multiple build configurations. So with the current implementation of the port in vcpkg unfortunately you will have to use the x64-windows triplet instead of the static one, and ship the dll along with your binary. Let me know if you have any idea to improve the vcpkg port,

**Comment by bangusi** [comment]
@victorburckel I don't have a better idea other than the desire to have static build. I thought a practical limitation may have been because ocilib needs to link to Oracle's oci.lib which is a proprietary library.
I always build my own ocilib static from source as I do with most libs that I use. Luckily vcpkg makes this very easy these days.

**Comment by victorburckel** [comment]
Ok, I may be wrong but I think the windows version of ocilib dynamically loads the oracle dlls (that's also what I did for the linux build by passing the --with-oracle-import=runtime to the configure script to be able to build without having the oracle distrib available), so ocilib could still be built as a static lib.
Do you currently build ocilib as a static lib ? If so do you use the provided sln / vcxproj in the proj/dll folder and add a new configuration (or maybe update the type to static lib instead of dll) ?
I guess if you want to automate that with vcpkg you can always add the new configuration and create a patch that would be applied to the source, and then select that configuration when built statically in vcpkg.

**Comment by bangusi** [comment]
@bangusi Yes, I build ocilib as a static lib.
No, I don't use the provided sln / vcxproj . I create a new project and add the sources.
Will look into your proposed approach. I am not really familiar with the ins and outs of vcpkg.
Was looking forward to do this
`vcpkg install ocilib:x64-windows-static`

and be done. Laziness I know but really vcpkg had been a god send.

**Comment by victorburckel** [comment]
Thanks for your response @bangusi 
Sorry I have an extra question, when you build the library, do you specify the preprocessor definition OCI_IMPORT_RUNTIME ? Otherwise I guess you're in OCI_IMPORT_LINKAGE which links the oracle library and you have to add oci.lib in your input libraries in Visual Studio (as you mentioned earlier).
The only issue with the linkage approach in vcpkg, is that there is no proper way to know where the oracle libraries are installed in windows (or maybe use ORACLE_HOME environment variable). Being a proprietary library, we cannot have vcpkg download and install it as a dependency of ocilib, we would have to rely on custom installation path.
So what can easily be done is, as mentioned earlier, add an extra static configuration by patching the vcxproj that would still rely on dynamic loading of the oracle libraries (built with OCI_IMPORT_RUNTIME), therefore you have to set your PATH properly or use the lib_path parameter in the OCI_Initialize function). If that's ok for you I can help you add this functionality to vcpkg and maybe submit that to the upstream sources.
What's a bit more complicated is having OCI_IMPORT_LINKAGE because we have to "guess" the library installation path, just as the two extra --with-oracle-lib-path and --with-oracle-headers-path for oracle instant client and --with-oracle-home for oracle regular installation. I'm a complete beginner when it comes to oracle, so I don't know what would be the good way to do this.

**Comment by bangusi** [comment]
@victorburckel This is my Visual Studio project

[ocilib_vs_project.zip](https://github.com/vrogier/ocilib/files/4705762/ocilib_vs_project.zip)

**Comment by vrogier** [comment]
closing this issue as vcpkg distribution has been since added
