### ISSUE TITLE
Should Column::GetSize() not return dictionary data_length?

### ISSUE THREAD

**Issue by bangusi** [vrogier/ocilib#231]
ANSI build on Windows. Oracle 12C

The DDL of my table column is declared as

`varchar2(8 char)`

The dictionary (user_tab_columns ) says:

```
data_length  = 32
char_col_decl_length =  32
```
In my code
`ocilib.Column::GetSize() returns 8`

which would appear consistent with the DDL. Problem is that the buffer size on my host variable is often insufficient if I rely on the result of `ocilib.Column::GetSize().`

Is there an alternative to ensure I get column size that is same as that reported in the column **data_length** of all_tab_columns?

**Comment by vrogier** [comment]
Hi,

the returned size is computed in the C API OCI_ColumnGetSize() :

`(col->charused && col->charsize > 0) ? col->charsize : col->size`

in your case col->size is 32 and col->charsize is 8. 
As the column is declared as using CHAR semantic, col->charsize is returned instead of col->size.

Right now that only thing you might do is have a wrapper like: 

```c++
auto GetColumnByteSize(Column& col)
{
    const auto MaxBytesPerChar = 4u;
    const auto factor = col.IsCharSemanticUsed() ? MaxBytesPerChar : 1u;

    return col.IsCharSemanticUsed() * factor;
}
```

I will see if I add a method OCI_ColumnGetByteSize() / Column::GetByteSize() for version 4.7.0

Regards,

Vincent

**Comment by bangusi** [comment]
I don't quite understand what you want to return here

` return col.IsCharSemanticUsed() * factor;`

a bool multiplied by a factor?

**Comment by vrogier** [comment]
I meant  col.GetSize() * factor.
I have edited my comment.
