### ISSUE TITLE
Statement::GetBind() raises exception

### ISSUE THREAD

**Issue by mrfazlali** [vrogier/ocilib#265]
Hi .
When i call  stmt.GetBind( name ) , it fails with "Error occured at OcilibStatementGetBind2: Item ':ID' (type 31)  not found".

Am i doing some sort of mistake ?

**Comment by vrogier** [comment]
Hi

This is the expected behaviour if the given bind  identified by ":ID" does not exist.

Regards,

Vincent

**Comment by mrfazlali** [comment]
Thanks for answer .
I'm trying to write a optional bind function . my input parameter is a std::optional<T>  . so if the optional parameter is null then i set null as bind .
Here is my optional bind. 

```
 template<typename T>
  inline void optional_bind(ocilib::Statement & stmt , const std::string & name ,  std::optional<T> & opt_value ,
            ocilib::BindInfo::BindDirection mode = ocilib::BindInfo::In)

    {
        if ( opt_value )
            stmt.Bind(name , opt_value.value() , mode);
        else
            stmt.GetBind(name).SetDataNull(true);
    }

```

and here is how i use it . 

```
bool select_functin( std::optional<int> & id_opt)
{
    ocilib::Statement stmt(conn);
    std::string sql = "select * from table where id = :id";     // **
    stmt.Prepare(sql);
    optional_bind(stmt , ":ID" , id_opt);
}
```

in * line i used :id as bind  .

**Comment by vrogier** [comment]
Hi,

OCILIB does not parse SQL statement to identify binds. 
Binds are created when calling Statement:Bind().
Statement::GetBind() returns bind objects that have previously created by Statement::Bind()

In your example, the bind object is created only if opt_value is not empty. Thus, if empty, you are calling GetBind() for a bind that does not exists, and get the exception.

You have to call Statement::Bind() to create the bind first.
And then call Bind::SetDataNull() if opt_value is empty.

In your worflow, while you don't have  a host variable for the bind operation, you stilll need to pass a reference to a host variable for Statement::Bind(), even if calling SetDataNull() later (which is just filling an indicator telling oracle client that whatever is the content of the variable, it should considered as NULL)

I would suggest using a custom optional wrapper class owing a T value (instead of directly using an optional<T>).
This class would need to implement constructor from T, assignment from T and bool and T operator and/or getters.

Vincent

**Comment by mrfazlali** [comment]
Thanks for the answer
