### ISSUE TITLE
C++ API Bind ostring has a memory leak

### ISSUE THREAD

**Issue by mlstar** [vrogier/ocilib#34]
Bind ostring  ,Visual Leak Detector detected a memory leak. in st.Bind(":1", test, 0, BindInfo::In); why? Bind use is not right?  not Call  ClearBinds()?
CODE:
```
int main()
{
	try
	{
		Environment::Initialize();
		Connection con;
		con.Open(dbs, usr, pwd, Environment::SessionDefault);
		ostring test= "test";
		Statement st(con);
		st.Prepare("declare v_ename varchar2(10); begin v_ename:= :1 ; end;");
		st.Bind(":1", test, 0, BindInfo::In);
		st.ExecutePrepared();
		con.Close();
	}
	catch (std::exception &ex)
	{
		std::cout << ex.what() << std::endl;
	}
	Environment::Cleanup();
	return EXIT_SUCCESS;
}
```

**Comment by vrogier** [comment]
Hi, 

This shall fix your issue. Let me know if everything is alright for you with the committed fix.

The issue was related to the scope and life time of your Statement object. If the Statement object had been destroyed prior to the close of the connection, no memory leak would have occurred.
Now, with the fix, the internal bind adapters are always freed regardless this scope and life time issue between Connection and Statement objects.

Thanks for reporting issue :)

Best regards,

Vincent

**Comment by mlstar** [comment]
Thank you very much, the leakage is solved, but the static method declared in header files, multiple files refer to "ocilib.hpp" will be a problem
```
error LNK2005: "private: static bool __cdecl ocilib::Statement::IsResultsetHandle(class ocilib::Handle *)
error LNK2005: "private: static void __cdecl ocilib::Statement::OnFreeSmartHandle(class ocilib::HandleHolder<struct OCI_Statement *>::SmartHandle *)
```

**Comment by vrogier** [comment]
I've just fixed it :)

It shall be fine now !
