### ISSUE TITLE
Question: cost of increasing OCI_BIND_MAX

### ISSUE THREAD

**Issue by FladoToo** [vrogier/ocilib#66]
Is there a downside to increasing OCI_BIND_MAX to, say, 32768?
I was unable to find an Oracle-imposed limit on the number of bind variables a SQL statement may have, and statements with over 20000 binds have been spotted in the wild...
We have to serve an Object-Relational Mapping layer which sometimes generates statements with way too many binds (in an OR-INLIST combination), but we have little control over what the ORM layer does.

**Comment by vrogier** [comment]
Hi,

As OCI_Bind arrays are currently allocated once, it would means each allocated OCI_Bind arrays (regular and register ones) to be 130Ko (32bit) or 260Ko (64bit)
Thus binding an simple int and register an short into the same statement would lead to allocated 260Ko / 520Ko (OCI_Bind arrays are only allocated when using OCI_BindXXX() and OCI_RegisterXXX() calls).

With current OCI_BIND_MAX value (1024) it is only 4Ko/8Ko.

Increasing the value would requires to performs OCI_Bind array reallocation by threshold in order to not pay the memory price whenever not needed.

It will try to put it in the v4.3.1 release :)

**Comment by vrogier** [comment]
Hi,

I've made a change and will commit it this weekend:
- Max bind set to max ushort value (oci limit as bind index is handled using ushort variable)
- internal oci_bind arrays are now reallocated on growth (by steps of 128 binds)
