### ISSUE TITLE
Unicode characters are not saved properly in NVARCHAR2 column

### ISSUE THREAD

**Issue by mikeyqin** [vrogier/ocilib#73]
My environment:
OS: Windows 10
OCILIB 4.3.1
Oracle server 12.1.0 on the same machine as my client
I built OciLib with RELEASE - Unicode configuration on Win64 platform with VS2015 (open the VS2013 solution file from VS2015 and upgrade the project file. See the attachment for project settings).
![project settings](https://cloud.githubusercontent.com/assets/19295227/22669763/f7b7eb4c-ec7a-11e6-88d9-bd4d5d748a29.jpg)

Here is my character set:
SELECT * FROM nls_database_parameters WHERE parameter LIKE '%CHARACTERSET%';
returns
NLS_NCHAR_CHARACTERSET   AL16UTF16
NLS_CHARACTERSET                 WE8MSWIN1252

My column userId is of type NVARCHAR2 (256).

Here is my script:
INSERT ALL INTO "Message" ("id", "userId") VALUES (N'CLS102', N'顶华')
SELECT * FROM dual;

If I call OCI_ExecuteStmt(statement, L"INSERT ALL INTO \"Message\" (\"id\", \"userId\") VALUES (N'CLS102', N'顶华')
SELECT * FROM dual;");
from a C++ program, the userId value will be upside-down question marks.

From Oracle's SQL Developer (v 4.1.1.9), I run the same insert statement, the userId value is inserted properly.

**Comment by vrogier** [comment]
Hi,

Have you called OCI_BindSetCharsetForm() with OCI_CSF_NATIONAL for the bind providing the value for 2nd column ?

Regards,

Vincent

**Comment by vrogier** [comment]
The problem is that the string you are using in your C/C++ program is interpreted by the compiler using its own non unicode locale, implying a transformation of the constant string content, e.g. each character converted to a different codepoint (63)
SQL Developper is an IDE (not a simple console program) that is doing things properly before executing the statement. The string you enetring in the IDE is properly converted to a unicode buffer with correct unicode codepoints

You will get the correct results with this code snippet:

```C
		cn = OCI_ConnectionCreate(dbs, usr, pwd, OCI_SESSION_DEFAULT);
		st = OCI_StatementCreate(cn);

		otext id[100] = OTEXT("CLS102");
		otext userid[100] = { 39030,  21326 };
		OCI_Prepare(st, L"INSERT INTO message (id, userId) VALUES (:1, :2)");
		OCI_BindString(st, OTEXT(":1"), id, 0);
		OCI_BindString(st, OTEXT(":2"), userid, 0);
		OCI_BindSetCharsetForm(OCI_GetBind(st, 1), OCI_CSF_NATIONAL);
		OCI_BindSetCharsetForm(OCI_GetBind(st, 2), OCI_CSF_NATIONAL);
		OCI_Execute(st);
		OCI_Commit(cn);
```

the unicode string '顶华' is composed of 2 UTF16 codepoints: U+9876 and U+534E.

A string litteral in your source code cannot represent these code points by default.
By initializing the "userid" string using code points and setting the bind as using national charsetform it works as expected (U+9876 is 39030 in decimal and  U+534E is 21326 in decimal)

**Comment by vrogier** [comment]
Note: if you save you source code file as unicode, you can use:

`	otext userid[100] = OTEXT("顶华");`

**Comment by vrogier** [comment]
the following:

`
		OCI_ExecuteStmt(st, L"INSERT INTO message (id, userId) VALUES (N'CLS444', N'顶华')");
`

is not working as expected even if the source file is saved as unicode.
Why ? Because, OCI originally does not handle nchar litteral in SQL statement string.
But in Oracle 10g, Oracle added support for nchar litteral ("N'") in SQL statement strings in unicode mode but it has to be activated explicitly by the program when initializing OCI. 
OCILIB is not performing this.
Thus, by passing the flag OCI_NCHAR_LITERAL_REPLACE_ON to OCIEnvCreate, the unicode sql string above gives the expected results.

I will add that flag to OCIEnvCreate() if ocilib charset is OCI_CHARSET_WIDE and OCI version >= 10g
